### ISSUE TITLE
Sion_R_Fully_Manual_Steer() doesn't work if there are other champion around Sion

### ISSUE THREAD

**Issue by jacklee-code** [Wafend/Sion#1]
Why does full manual steering mode not work if there are champions around the Sion. I have check the code of manual steer and I don't find any logical problem.
`ObjectManager.Player.IssueOrder(GameObjectOrder.AttackMove, Game.CursorPos);`

However, if Sion has an enemy champion around him, even with manual steering, Sion will collide with the nearest champion, making it impossible for me to target a certain champion.

**Comment by Wafend** [comment]
Personally i would recommend you to use "Beast_Mode" as it basically fixes this issue in a ghetto way

So since we use AttackMove, just like if you play legit with "Player Attack Move Click", it will attack the nearest target either to your champion or cursor. Therefore, if Sion is near attackable units such as towers, inhibs, minions, champions even wards and so on, sion will not be able to steer to his mouse

What I beast mode is to declare a radius for minions or champions near your minions which you can use for anchors to redirect your ult to. So whenever you're in a wave of minions where Manual Steer doesn't work, you can still redirect your ult if you hover your cursor over an attackable unit, in this case minions or champions
